package com.github.alexthe666.alexsmobs.client.render;

import com.github.alexthe666.alexsmobs.entity.AMEntityRegistry;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import net.minecraft.world.entity.EntityType;

public class AMMobIcons {
   private static final List<Pair<EntityType, Float>> MOB_ICONS = List.of(
      new Pair((EntityType)AMEntityRegistry.GRIZZLY_BEAR.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.ROADRUNNER.get(), 0.8F),
      new Pair((EntityType)AMEntityRegistry.BONE_SERPENT.get(), 0.55F),
      new Pair((EntityType)AMEntityRegistry.GAZELLE.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.CROCODILE.get(), 0.3F),
      new Pair((EntityType)AMEntityRegistry.FLY.get(), 1.3F),
      new Pair((EntityType)AMEntityRegistry.HUMMINGBIRD.get(), 1.5F),
      new Pair((EntityType)AMEntityRegistry.ORCA.get(), 0.2F),
      new Pair((EntityType)AMEntityRegistry.SUNBIRD.get(), 0.2F),
      new Pair((EntityType)AMEntityRegistry.GORILLA.get(), 0.85F),
      new Pair((EntityType)AMEntityRegistry.CRIMSON_MOSQUITO.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.RATTLESNAKE.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.ENDERGRADE.get(), 0.8F),
      new Pair((EntityType)AMEntityRegistry.HAMMERHEAD_SHARK.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.LOBSTER.get(), 0.85F),
      new Pair((EntityType)AMEntityRegistry.KOMODO_DRAGON.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.CAPUCHIN_MONKEY.get(), 0.85F),
      new Pair((EntityType)AMEntityRegistry.CENTIPEDE_HEAD.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.WARPED_TOAD.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.MOOSE.get(), 0.38F),
      new Pair((EntityType)AMEntityRegistry.MIMICUBE.get(), 0.95F),
      new Pair((EntityType)AMEntityRegistry.RACCOON.get(), 0.8F),
      new Pair((EntityType)AMEntityRegistry.BLOBFISH.get(), 1.0F),
      new Pair((EntityType)AMEntityRegistry.SEAL.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.COCKROACH.get(), 1.0F),
      new Pair((EntityType)AMEntityRegistry.SHOEBILL.get(), 0.8F),
      new Pair((EntityType)AMEntityRegistry.ELEPHANT.get(), 0.3F),
      new Pair((EntityType)AMEntityRegistry.SOUL_VULTURE.get(), 0.8F),
      new Pair((EntityType)AMEntityRegistry.SNOW_LEOPARD.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.SPECTRE.get(), 0.3F),
      new Pair((EntityType)AMEntityRegistry.CROW.get(), 1.3F),
      new Pair((EntityType)AMEntityRegistry.ALLIGATOR_SNAPPING_TURTLE.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.MUNGUS.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.MANTIS_SHRIMP.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.GUSTER.get(), 0.55F),
      new Pair((EntityType)AMEntityRegistry.WARPED_MOSCO.get(), 0.35F),
      new Pair((EntityType)AMEntityRegistry.STRADDLER.get(), 0.38F),
      new Pair((EntityType)AMEntityRegistry.STRADPOLE.get(), 0.9F),
      new Pair((EntityType)AMEntityRegistry.EMU.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.PLATYPUS.get(), 1.0F),
      new Pair((EntityType)AMEntityRegistry.DROPBEAR.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.TASMANIAN_DEVIL.get(), 1.2F),
      new Pair((EntityType)AMEntityRegistry.KANGAROO.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.CACHALOT_WHALE.get(), 0.1F),
      new Pair((EntityType)AMEntityRegistry.LEAFCUTTER_ANT.get(), 1.2F),
      new Pair((EntityType)AMEntityRegistry.ENDERIOPHAGE.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.BALD_EAGLE.get(), 0.85F),
      new Pair((EntityType)AMEntityRegistry.TIGER.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.TARANTULA_HAWK.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.VOID_WORM.get(), 0.3F),
      new Pair((EntityType)AMEntityRegistry.FRILLED_SHARK.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.MIMIC_OCTOPUS.get(), 0.7F),
      new Pair((EntityType)AMEntityRegistry.SEAGULL.get(), 1.2F),
      new Pair((EntityType)AMEntityRegistry.FROSTSTALKER.get(), 0.8F),
      new Pair((EntityType)AMEntityRegistry.TUSKLIN.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.LAVIATHAN.get(), 0.2F),
      new Pair((EntityType)AMEntityRegistry.COSMAW.get(), 0.32F),
      new Pair((EntityType)AMEntityRegistry.TOUCAN.get(), 1.3F),
      new Pair((EntityType)AMEntityRegistry.MANED_WOLF.get(), 0.85F),
      new Pair((EntityType)AMEntityRegistry.ANACONDA.get(), 1.0F),
      new Pair((EntityType)AMEntityRegistry.ANTEATER.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.ROCKY_ROLLER.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.FLUTTER.get(), 1.15F),
      new Pair((EntityType)AMEntityRegistry.GELADA_MONKEY.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.JERBOA.get(), 1.3F),
      new Pair((EntityType)AMEntityRegistry.TERRAPIN.get(), 1.1F),
      new Pair((EntityType)AMEntityRegistry.COMB_JELLY.get(), 1.0F),
      new Pair((EntityType)AMEntityRegistry.COSMIC_COD.get(), 1.3F),
      new Pair((EntityType)AMEntityRegistry.BUNFUNGUS.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.BISON.get(), 0.45F),
      new Pair((EntityType)AMEntityRegistry.GIANT_SQUID.get(), 0.3F),
      new Pair((EntityType)AMEntityRegistry.DEVILS_HOLE_PUPFISH.get(), 1.4F),
      new Pair((EntityType)AMEntityRegistry.CATFISH.get(), 1.15F),
      new Pair((EntityType)AMEntityRegistry.FLYING_FISH.get(), 1.2F),
      new Pair((EntityType)AMEntityRegistry.SKELEWAG.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.RAIN_FROG.get(), 1.8F),
      new Pair((EntityType)AMEntityRegistry.POTOO.get(), 1.2F),
      new Pair((EntityType)AMEntityRegistry.MUDSKIPPER.get(), 1.2F),
      new Pair((EntityType)AMEntityRegistry.RHINOCEROS.get(), 0.4F),
      new Pair((EntityType)AMEntityRegistry.SUGAR_GLIDER.get(), 1.3F),
      new Pair((EntityType)AMEntityRegistry.FARSEER.get(), 0.6F),
      new Pair((EntityType)AMEntityRegistry.SKREECHER.get(), 0.77F),
      new Pair((EntityType)AMEntityRegistry.UNDERMINER.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.MURMUR.get(), 0.65F),
      new Pair((EntityType)AMEntityRegistry.SKUNK.get(), 1.0F),
      new Pair((EntityType)AMEntityRegistry.BANANA_SLUG.get(), 1.5F),
      new Pair((EntityType)AMEntityRegistry.BLUE_JAY.get(), 1.4F),
      new Pair((EntityType)AMEntityRegistry.CAIMAN.get(), 0.5F),
      new Pair((EntityType)AMEntityRegistry.TRIOPS.get(), 0.95F)
   );

   public static List<Pair<EntityType, Float>> getMobIcons() {
      return MOB_ICONS;
   }
}
